# Generate Customer Data by means of OOP

In this sub-project, I create 1000 simulated customer data. This data is the basis for the subsequent sub-projects.

0. Import Libraries and do general settings

In [1]:
!pip install XlsxWriter

Requirement already satisfied: XlsxWriter in c:\users\felis\.conda\envs\gee\lib\site-packages (3.1.2)

In [2]:
import random
import pandas as pd
import numpy as np

In [3]:
# set a random.seed
random.seed(12)

1. Create a Parent Class for Personal Information

In [4]:
class Customer():
    # holds details about the customer
    def __init__(self, ID, age, city, gender):
        self.ID = ID
        self.age = age
        self.city = city
        self.gender = gender
        
    def show_details(self): # has access to attributes
        print("Personal Details")
        print("")
        print("ID:", self.ID)
        print("Age:", self.age)
        print("City:", self.city)
        print("Gender:", self.gender)

2. Create 1000 instances for the parent class.

Instead of adding 1000 objects individually, I create a dataframe and convert its rows into objects later on.

In accordance with the class, I create four columns: ID, age, city and gender. I merge them in a dataframe.

In [5]:
k = 1000 # number of rows / instances

2.1. ID

In [6]:
list_id = list(range(1,1001))

2.2. Age

In [7]:
# Assume only customers between 20 and 60 can get a credit. The distribution of age groups is as follows:
# 20 - 25: 0.15 percent, 26 - 40 = 0.4, 41 - 55 = 0. 35, 56 - 60 = 0.1
weight1 = 0.15
weight2 = 0.4
weight3 = 0.35
weight4 = 0.1

list_age = (
    [random.randint(20, 25) for _ in range(int(k * weight1))]
    + [random.randint(26, 40) for _ in range(int(k * weight2))]
    + [random.randint(41, 55) for _ in range(int(k * weight3))]
    + [random.randint(56, 60) for _ in range(int(k * weight4))]
)

2.3. City

In [8]:
# I limit the cities to four cities and apply weights. This decision is completely arbitrary, but it facilitates a risk assessment later on
list_cities = (
    ["Hamburg" for _ in range(int(k * 0.2))]
    + ["Berlin" for _ in range(int(k * 0.1))]
    + ["Frankfurt" for _ in range(int(k * 0.4))]
    + ["München" for _ in range(int(k * 0.3))]
)

random.shuffle(list_cities)

2.4. Gender

In [9]:
# 2% of gender is diverse, the remaining male and female are balanced
gender = ["female", "male", "diverse"]
num_diverse = int(1000 * 0.02)
num_female = (1000 - num_diverse) // 2
num_male = 1000 - num_diverse - num_female

list_gender = ["diverse"] * num_diverse + ["male"] * num_male + ["female"] * num_female

random.shuffle(list_gender)

In [10]:
# check if the gender distribution is as expeczed (it is)
pd.DataFrame(list_gender).value_counts()

female     490
male       490
diverse     20
Name: count, dtype: int64

2.5. Merge lists in a dataframe

In [11]:
details = [list_id, list_age, list_cities, list_gender]

In [12]:
details_df = pd.DataFrame(details)

In [13]:
details_df = details_df.transpose()

In [14]:
details_df.head()

   0   1          2       3
0  1  23  Frankfurt  female
1  2  22    München    male
2  3  25    Hamburg  female
3  4  24    München  female
4  5  25    München    male

In [15]:
details_df.rename(columns = {0: "ID", 1: "Age", 2: "City", 3: "Gender"}, inplace = True)

2.6. Match Customer class with details_df dataframe

In [16]:
customers = []
for index, row in details_df.iterrows():
    customer = Customer(row['ID'], row['Age'], row['City'], row['Gender'])
    customers.append(customer)

In [17]:
for customer in customers:
    print("ID:", customer.ID)
    print("Age:", customer.age)
    print("City:", customer.city)
    print("Gender:", customer.gender)
    print("--------------------")

ID: 1
Age: 23
City: Frankfurt
Gender: female
--------------------
ID: 2
Age: 22
City: München
Gender: male
--------------------
ID: 3
Age: 25
City: Hamburg
Gender: female
--------------------
ID: 4
Age: 24
City: München
Gender: female
--------------------
ID: 5
Age: 25
City: München
Gender: male
--------------------
ID: 6
Age: 22
City: Frankfurt
Gender: female
--------------------
ID: 7
Age: 21
City: Frankfurt
Gender: female
--------------------
ID: 8
Age: 23
City: Hamburg
Gender: female
--------------------
ID: 9
Age: 20
City: Hamburg
Gender: female
--------------------
ID: 10
Age: 22
City: Frankfurt
Gender: male
--------------------
ID: 11
Age: 23
City: Frankfurt
Gender: male
--------------------
ID: 12
Age: 22
City: München
Gender: female
--------------------
ID: 13
Age: 25
City: Frankfurt
Gender: male
--------------------
ID: 14
Age: 23
City: Berlin
Gender: female
--------------------
ID: 15
Age: 25
City: Hamburg
Gender: female
--------------------
ID: 16
Age: 24
City: Hamburg
Gender: female
--------------------
ID: 17
Age: 21
City: München
Gender: male
--------------------
ID: 18
Age: 24
City: Hamburg
Gender: male
--------------------
ID: 19
Age: 20
City: München
Gender: female
--------------------
ID: 20
Age: 25
City: München
Gender: male
--------------------
ID: 21
Age: 24
City: Frankfurt
Gender: female
--------------------
ID: 22
Age: 21
City: Frankfurt
Gender: female
--------------------
ID: 23
Age: 23
City: Hamburg
Gender: female
--------------------
ID: 24
Age: 22
City: München
Gender: male
--------------------
ID: 25
Age: 21
City: Hamburg
Gender: male
--------------------
ID: 26
Age: 22
City: München
Gender: male
--------------------
ID: 27
Age: 21
City: Frankfurt
Gender: male
--------------------
ID: 28
Age: 20
City: München
Gender: female
--------------------
ID: 29
Age: 24
City: Berlin
Gender: female
--------------------
ID: 30
Age: 21
City: Berlin
Gender: female
--------------------
ID: 31
Age: 20
City: Frankfurt
Gender: male
--------------------
ID: 32
Age: 24
City: Frankfurt
Gender: male
--------------------
ID: 33
Age: 25
City: Frankfurt
Gender: male
--------------------
ID: 34
Age: 22
City: München
Gender: male
--------------------
ID: 35
Age: 25
City: Frankfurt
Gender: female
--------------------
ID: 36
Age: 23
City: München
Gender: female
--------------------
ID: 37
Age: 20
City: Frankfurt
Gender: male
--------------------
ID: 38
Age: 20
City: Frankfurt
Gender: female
--------------------
ID: 39
Age: 20
City: Berlin
Gender: female
--------------------
ID: 40
Age: 25
City: Berlin
Gender: female
--------------------
ID: 41
Age: 24
City: Frankfurt
Gender: female
--------------------
ID: 42
Age: 21
City: München
Gender: male
--------------------
ID: 43
Age: 20
City: Frankfurt
Gender: male
--------------------
ID: 44
Age: 23
City: Hamburg
Gender: male
--------------------
ID: 45
Age: 23
City: Frankfurt
Gender: female
--------------------
ID: 46
Age: 20
City: München
Gender: female
--------------------
ID: 47
Age: 25
City: München
Gender: female
--------------------
ID: 48
Age: 23
City: München
Gender: female
--------------------
ID: 49
Age: 21
City: Frankfurt
Gender: female
--------------------
ID: 50
Age: 24
City: München
Gender: female
--------------------
ID: 51
Age: 22
City: Frankfurt
Gender: female
--------------------
ID: 52
Age: 24
City: München
Gender: male
--------------------
ID: 53
Age: 24
City: München
Gender: female
--------------------
ID: 54
Age: 21
City: Frankfurt
Gender: male
--------------------
ID: 55
Age: 25
City: Hamburg
Gender: male
--------------------
ID: 56
Age: 20
City: Berlin
Gender: male
--------------------
ID: 57
Age: 24
City: Frankfurt
Gender: male
--------------------
ID: 58
Age: 21
City: München
Gender: female
--------------------
ID: 59
Age: 24
City: München
Gender: male
--------------------
ID: 60
Age: 20
City: Hamburg
Gender: male
--------------------
ID: 61
Age: 23
City: Hamburg
Gender: male
--------------------
ID: 62
Age: 24
City: München
Gender: female
--------------------
ID: 63
Age: 23
City: Frankfurt
Gender: male
--------------------
ID: 64
Age: 25
City: München
Gender: female
--------------------
ID: 65
Age: 24
City: Berlin
Gender: male
--------------------
ID: 66
Age: 23
City: Hamburg
Gender: female
--------------------
ID: 67
Age: 23
City: Frankfurt
Gender: male
--------------------
ID: 68
Age: 24
City: Frankfurt
Gender: male
--------------------
ID: 69
Age: 23
City: Frankfurt
Gender: female
--------------------
ID: 70
Age: 24
City: München
Gender: female
--------------------
ID: 71
Age: 20
City: Frankfurt
Gender: female
--------------------
ID: 72
Age: 25
City: Berlin
Gender: male
--------------------
ID: 73
Age: 25
City: Frankfurt
Gender: male
--------------------
ID: 74
Age: 20
City: Berlin
Gender: female
--------------------
ID: 75
Age: 21
City: Frankfurt
Gender: male
--------------------
ID: 76
Age: 25
City: Berlin
Gender: female
--------------------
ID: 77
Age: 22
City: Frankfurt
Gender: male
--------------------
ID: 78
Age: 22
City: München
Gender: female
--------------------
ID: 79
Age: 22
City: Hamburg
Gender: female
--------------------
ID: 80
Age: 25
City: Hamburg
Gender: male
--------------------
ID: 81
Age: 23
City: Frankfurt
Gender: male
--------------------
ID: 82
Age: 25
City: Hamburg
Gender: male
--------------------
ID: 83
Age: 22
City: München
Gender: male
--------------------
ID: 84
Age: 20
City: Frankfurt
Gender: male
--------------------
ID: 85
Age: 22
City: Frankfurt
Gender: male
--------------------
ID: 86
Age: 21
City: Berlin
Gender: female
--------------------
ID: 87
Age: 22
City: München
Gender: female
--------------------
ID: 88
Age: 22
City: Frankfurt
Gender: male
--------------------
ID: 89
Age: 22
City: Frankfurt
Gender: female
--------------------
ID: 90
Age: 24
City: Frankfurt
Gender: male
--------------------
ID: 91
Age: 24
City: Hamburg
Gender: male
--------------------
ID: 92
Age: 24
City: München
Gender: female
--------------------
ID: 93
Age: 21
City: Berlin
Gender: male
--------------------
ID: 94
Age: 20
City: Hamburg
Gender: female
--------------------
ID: 95
Age: 23
City: München
Gender: male
--------------------
ID: 96
Age: 23
City: Frankfurt
Gender: male
--------------------
ID: 97
Age: 20
City: Frankfurt
Gender: male
--------------------
ID: 98
Age: 24
City: Berlin
Gender: female
--------------------
ID: 99
Age: 20
City: Hamburg
Gender: male
--------------------
ID: 100
Age: 21
City: Berlin
Gender: female
--------------------
ID: 101
Age: 25
City: Berlin
Gender: female
--------------------
ID: 102
Age: 23
City: Hamburg
Gender: female
--------------------
ID: 103
Age: 20
City: Frankfurt
Gender: male
--------------------
ID: 104
Age: 23
City: Frankfurt
Gender: female
--------------------
ID: 105
Age: 21
City: München
Gender: male
--------------------
ID: 106
Age: 24
City: Frankfurt
Gender: male
--------------------
ID: 107
Age: 20
City: Frankfurt
Gender: female
--------------------
ID: 108
Age: 24
City: Frankfurt
Gender: male
--------------------
ID: 109
Age: 21
City: München
Gender: male
--------------------
ID: 110
Age: 21
City: München
Gender: male
--------------------
ID: 111
Age: 20
City: München
Gender: female
--------------------
ID: 112
Age: 25
City: Berlin
Gender: female
--------------------
ID: 113
Age: 22
City: Hamburg
Gender: diverse
--------------------
ID: 114
Age: 20
City: Frankfurt
Gender: male
--------------------
ID: 115
Age: 23
City: Frankfurt
Gender: male
--------------------
ID: 116
Age: 22
City: München
Gender: female
--------------------
ID: 117
Age: 23
City: München
Gender: male
--------------------
ID: 118
Age: 22
City: Frankfurt
Gender: female
--------------------
ID: 119
Age: 24
City: München
Gender: male
--------------------
ID: 120
Age: 25
City: Hamburg
Gender: female
--------------------
ID: 121
Age: 25
City: Frankfurt
Gender: male
--------------------
ID: 122
Age: 20
City: Frankfurt
Gender: female
--------------------
ID: 123
Age: 24
City: München
Gender: female
--------------------
ID: 124
Age: 23
City: Frankfurt
Gender: male
--------------------
ID: 125
Age: 22
City: Frankfurt
Gender: male
--------------------
ID: 126
Age: 21
City: Frankfurt
Gender: female
--------------------
ID: 127
Age: 22
City: Berlin
Gender: male
--------------------
ID: 128
Age: 22
City: Frankfurt
Gender: male
--------------------
ID: 129
Age: 23
City: München
Gender: male
--------------------
ID: 130
Age: 23
City: Frankfurt
Gender: female
--------------------
ID: 131
Age: 25
City: Frankfurt
Gender: female
--------------------
ID: 132
Age: 23
City: München
Gender: female
--------------------
ID: 133
Age: 21
City: München
Gender: female
--------------------
ID: 134
Age: 21
City: Frankfurt
Gender: female
--------------------
ID: 135
Age: 23
City: Berlin
Gender: female
--------------------
ID: 136
Age: 24
City: München
Gender: male
--------------------
ID: 137
Age: 22
City: Frankfurt
Gender: female
--------------------
ID: 138
Age: 21
City: Hamburg
Gender: female
--------------------
ID: 139
Age: 21
City: München
Gender: female
--------------------
ID: 140
Age: 25
City: Frankfurt
Gender: male
--------------------
ID: 141
Age: 21
City: München
Gender: female
--------------------
ID: 142
Age: 24
City: Hamburg
Gender: female
--------------------
ID: 143
Age: 20
City: Frankfurt
Gender: female
--------------------
ID: 144
Age: 22
City: Frankfurt
Gender: male
--------------------
ID: 145
Age: 22
City: Hamburg
Gender: male
--------------------
ID: 146
Age: 21
City: München
Gender: female
--------------------
ID: 147
Age: 21
City: Hamburg
Gender: female
--------------------
ID: 148
Age: 20
City: München
Gender: female
--------------------
ID: 149
Age: 24
City: München
Gender: male
--------------------
ID: 150
Age: 20
City: Hamburg
Gender: female
--------------------
ID: 151
Age: 29
City: Berlin
Gender: female
--------------------
ID: 152
Age: 35
City: München
Gender: female
--------------------
ID: 153
Age: 27
City: Frankfurt
Gender: female
--------------------
ID: 154
Age: 31
City: Frankfurt
Gender: female
--------------------
ID: 155
Age: 34
City: Hamburg
Gender: female
--------------------
ID: 156
Age: 34
City: Berlin
Gender: female
--------------------
ID: 157
Age: 28
City: Hamburg
Gender: female
--------------------
ID: 158
Age: 26
City: Frankfurt
Gender: female
--------------------
ID: 159
Age: 40
City: Frankfurt
Gender: female
--------------------
ID: 160
Age: 31
City: Frankfurt
Gender: male
--------------------
ID: 161
Age: 40
City: Frankfurt
Gender: male
--------------------
ID: 162
Age: 38
City: Frankfurt
Gender: female
--------------------
ID: 163
Age: 36
City: Hamburg
Gender: female
--------------------
ID: 164
Age: 39
City: Frankfurt
Gender: male
--------------------
ID: 165
Age: 30
City: Frankfurt
Gender: male
--------------------
ID: 166
Age: 36
City: München
Gender: male
--------------------
ID: 167
Age: 27
City: München
Gender: male
--------------------
ID: 168
Age: 29
City: München
Gender: female
--------------------
ID: 169
Age: 38
City: Frankfurt
Gender: male
--------------------
ID: 170
Age: 34
City: München
Gender: female
--------------------
ID: 171
Age: 34
City: Frankfurt
Gender: male
--------------------
ID: 172
Age: 33
City: Hamburg
Gender: male
--------------------
ID: 173
Age: 33
City: München
Gender: male
--------------------
ID: 174
Age: 36
City: München
Gender: female
--------------------
ID: 175
Age: 31
City: Hamburg
Gender: male
--------------------
ID: 176
Age: 30
City: Frankfurt
Gender: male
--------------------
ID: 177
Age: 36
City: München
Gender: female
--------------------
ID: 178
Age: 33
City: Berlin
Gender: female
--------------------
ID: 179
Age: 40
City: Frankfurt
Gender: male
--------------------
ID: 180
Age: 37
City: Frankfurt
Gender: male
--------------------
ID: 181
Age: 28
City: Frankfurt
Gender: female
--------------------
ID: 182
Age: 33
City: München
Gender: male
--------------------
ID: 183
Age: 30
City: München
Gender: female
--------------------
ID: 184
Age: 35
City: München
Gender: female
--------------------
ID: 185
Age: 39
City: Hamburg
Gender: female
--------------------
ID: 186
Age: 26
City: Hamburg
Gender: female
--------------------
ID: 187
Age: 30
City: München
Gender: female
--------------------
ID: 188
Age: 31
City: München
Gender: male
--------------------
ID: 189
Age: 39
City: Frankfurt
Gender: male
--------------------
ID: 190
Age: 34
City: Frankfurt
Gender: female
--------------------
ID: 191
Age: 36
City: Hamburg
Gender: male
--------------------
ID: 192
Age: 37
City: Frankfurt
Gender: female
--------------------
ID: 193
Age: 33
City: München
Gender: male
--------------------
ID: 194
Age: 37
City: München
Gender: male
--------------------
ID: 195
Age: 38
City: Frankfurt
Gender: female
--------------------
ID: 196
Age: 29
City: Berlin
Gender: female
--------------------
ID: 197
Age: 37
City: Frankfurt
Gender: female
--------------------
ID: 198
Age: 30
City: München
Gender: female
--------------------
ID: 199
Age: 34
City: Frankfurt
Gender: male
--------------------
ID: 200
Age: 30
City: München
Gender: female
--------------------
ID: 201
Age: 26
City: Berlin
Gender: female
--------------------
ID: 202
Age: 36
City: Frankfurt
Gender: female
--------------------
ID: 203
Age: 26
City: Frankfurt
Gender: female
--------------------
ID: 204
Age: 37
City: Hamburg
Gender: female
--------------------
ID: 205
Age: 26
City: München
Gender: male
--------------------
ID: 206
Age: 28
City: Frankfurt
Gender: male
--------------------
ID: 207
Age: 34
City: München
Gender: female
--------------------
ID: 208
Age: 40
City: Frankfurt
Gender: male
--------------------
ID: 209
Age: 30
City: Frankfurt
Gender: male
--------------------
ID: 210
Age: 32
City: Hamburg
Gender: male
--------------------
ID: 211
Age: 28
City: Hamburg
Gender: male
--------------------
ID: 212
Age: 29
City: München
Gender: male
--------------------
ID: 213
Age: 29
City: München
Gender: male
--------------------
ID: 214
Age: 32
City: Frankfurt
Gender: diverse
--------------------
ID: 215
Age: 33
City: Berlin
Gender: female
--------------------
ID: 216
Age: 26
City: Hamburg
Gender: female
--------------------
ID: 217
Age: 34
City: München
Gender: female
--------------------
ID: 218
Age: 35
City: München
Gender: male
--------------------
ID: 219
Age: 35
City: München
Gender: female
--------------------
ID: 220
Age: 37
City: Hamburg
Gender: male
--------------------
ID: 221
Age: 40
City: München
Gender: male
--------------------
ID: 222
Age: 40
City: Hamburg
Gender: male
--------------------
ID: 223
Age: 30
City: München
Gender: male
--------------------
ID: 224
Age: 38
City: Frankfurt
Gender: male
--------------------
ID: 225
Age: 26
City: Hamburg
Gender: female
--------------------
ID: 226
Age: 32
City: Frankfurt
Gender: male
--------------------
ID: 227
Age: 32
City: Frankfurt
Gender: male
--------------------
ID: 228
Age: 35
City: Frankfurt
Gender: male
--------------------
ID: 229
Age: 27
City: Hamburg
Gender: male
--------------------
ID: 230
Age: 40
City: Hamburg
Gender: female
--------------------
ID: 231
Age: 32
City: Berlin
Gender: male
--------------------
ID: 232
Age: 38
City: Frankfurt
Gender: diverse
--------------------
ID: 233
Age: 29
City: Frankfurt
Gender: female
--------------------
ID: 234
Age: 35
City: Hamburg
Gender: male
--------------------
ID: 235
Age: 34
City: Frankfurt
Gender: male
--------------------
ID: 236
Age: 31
City: München
Gender: male
--------------------
ID: 237
Age: 31
City: Hamburg
Gender: female
--------------------
ID: 238
Age: 36
City: München
Gender: diverse
--------------------
ID: 239
Age: 37
City: München
Gender: male
--------------------
ID: 240
Age: 32
City: Hamburg
Gender: female
--------------------
ID: 241
Age: 35
City: Hamburg
Gender: male
--------------------
ID: 242
Age: 28
City: München
Gender: male
--------------------
ID: 243
Age: 26
City: München
Gender: male
--------------------
ID: 244
Age: 37
City: Frankfurt
Gender: female
--------------------
ID: 245
Age: 37
City: Frankfurt
Gender: female
--------------------
ID: 246
Age: 28
City: Frankfurt
Gender: female
--------------------
ID: 247
Age: 40
City: Frankfurt
Gender: male
--------------------
ID: 248
Age: 26
City: Hamburg
Gender: female
--------------------
ID: 249
Age: 38
City: Frankfurt
Gender: female
--------------------
ID: 250
Age: 26
City: München
Gender: female
--------------------
ID: 251
Age: 40
City: Frankfurt
Gender: diverse
--------------------
ID: 252
Age: 27
City: Frankfurt
Gender: male
--------------------
ID: 253
Age: 40
City: München
Gender: diverse
--------------------
ID: 254
Age: 32
City: München
Gender: female
--------------------
ID: 255
Age: 34
City: München
Gender: male
--------------------
ID: 256
Age: 29
City: Hamburg
Gender: male
--------------------
ID: 257
Age: 38
City: München
Gender: female
--------------------
ID: 258
Age: 40
City: Frankfurt
Gender: male
--------------------
ID: 259
Age: 32
City: München
Gender: female
--------------------
ID: 260
Age: 38
City: Frankfurt
Gender: female
--------------------
ID: 261
Age: 27
City: München
Gender: female
--------------------
ID: 262
Age: 37
City: Berlin
Gender: male
--------------------
ID: 263
Age: 31
City: Frankfurt
Gender: male
--------------------
ID: 264
Age: 29
City: München
Gender: male
--------------------
ID: 265
Age: 30
City: München
Gender: female
--------------------
ID: 266
Age: 30
City: München
Gender: male
--------------------
ID: 267
Age: 40
City: Frankfurt
Gender: female
--------------------
ID: 268
Age: 38
City: Frankfurt
Gender: female
--------------------
ID: 269
Age: 37
City: Frankfurt
Gender: female
--------------------
ID: 270
Age: 36
City: Frankfurt
Gender: male
--------------------
ID: 271
Age: 34
City: Berlin
Gender: female
--------------------
ID: 272
Age: 33
City: Frankfurt
Gender: male
--------------------
ID: 273
Age: 35
City: Frankfurt
Gender: male
--------------------
ID: 274
Age: 35
City: Hamburg
Gender: male
--------------------
ID: 275
Age: 27
City: Hamburg
Gender: male
--------------------
ID: 276
Age: 29
City: München
Gender: male
--------------------
ID: 277
Age: 34
City: Frankfurt
Gender: male
--------------------
ID: 278
Age: 35
City: München
Gender: male
--------------------
ID: 279
Age: 37
City: Frankfurt
Gender: female
--------------------
ID: 280
Age: 36
City: Frankfurt
Gender: female
--------------------
ID: 281
Age: 32
City: München
Gender: male
--------------------
ID: 282
Age: 35
City: Hamburg
Gender: female
--------------------
ID: 283
Age: 29
City: Berlin
Gender: male
--------------------
ID: 284
Age: 27
City: München
Gender: female
--------------------
ID: 285
Age: 32
City: Hamburg
Gender: male
--------------------
ID: 286
Age: 31
City: Hamburg
Gender: male
--------------------
ID: 287
Age: 31
City: München
Gender: male
--------------------
ID: 288
Age: 27
City: Hamburg
Gender: female
--------------------
ID: 289
Age: 36
City: Frankfurt
Gender: male
--------------------
ID: 290
Age: 31
City: Frankfurt
Gender: female
--------------------
ID: 291
Age: 28
City: Berlin
Gender: diverse
--------------------
ID: 292
Age: 36
City: Hamburg
Gender: male
--------------------
ID: 293
Age: 27
City: München
Gender: male
--------------------
ID: 294
Age: 37
City: Berlin
Gender: female
--------------------
ID: 295
Age: 30
City: Frankfurt
Gender: male
--------------------
ID: 296
Age: 30
City: Berlin
Gender: female
--------------------
ID: 297
Age: 37
City: Hamburg
Gender: female
--------------------
ID: 298
Age: 28
City: Hamburg
Gender: male
--------------------
ID: 299
Age: 38
City: Hamburg
Gender: male
--------------------
ID: 300
Age: 36
City: München
Gender: female
--------------------
ID: 301
Age: 36
City: Hamburg
Gender: male
--------------------
ID: 302
Age: 36
City: Frankfurt
Gender: female
--------------------
ID: 303
Age: 40
City: Frankfurt
Gender: male
--------------------
ID: 304
Age: 32
City: Frankfurt
Gender: male
--------------------
ID: 305
Age: 31
City: München
Gender: male
--------------------
ID: 306
Age: 28
City: Frankfurt
Gender: diverse

2. Create a Child Class for Credit-Related Data

In [18]:
class CreditScore(Customer): # inherit property and methods from user class
    
    def __init__(self, name, age, city, gender):
        super().__init__(name, age, city, gender) # superfunction avoids us to write self.name, self.age and self.gender again
        
    def paymenthistory(self, payment_history):
        self.payment_history = payment_history
        
    def nolatepayments(self, nolatepayments):
        self.nolatepayments = nolatepayments
        
    def timelatepayments(self, timelatepayments):
        self.timelatepayments = timelatepayments
        
    def amountsowed(self, credit_used, credit_available):
        self.credit_used = credit_used 
        self.credit_available = credit_available
        self.calculate_amounts_owed()

    # def calculate_amounts_owed(self):
        #if self.credit_available != 0:
            #self.amounts_owed = self.credit_used / self.credit_available
        #else:
            #self.amounts_owed = 0
             
    def lengthcredithistory(self, lengthcredithistory):
        self.lengthcredithistory = lengthcredithistory
        
    def creditmix(self, creditmix): # ask user for number of types
        self.creditmix = creditmix
        
    def newcredit(self, newcredit): # ask for new applications in the last 12 months
        self.newcredit = newcredit

3. Create 1000 instances for the child class.

According to https://www.investopedia.com/terms/c/credit_score.asp, the following data is needed:

- payment history: Your payment history includes whether you've paid your bills on time. It takes into account how many late payments you've had, and how late they were.
- amounts owed: Amounts owed is the percentage of credit you've used compared to the credit available to you, which is known as credit utilization.
- length of credit history: Longer credit histories are considered less risky, as there is more data to determine payment history.
- credit mix: A variety of credit types shows lenders you can manage various types of credit. It can include installment credit, such as car loans or mortgage loans, and revolving credit, such as credit cards.
- new credit: Lenders view new credit as a potential sign you may be desperate for credit. Too many recent applications for credit can negatively affect your credit score.

I create a list for each of these components. I add the respective list to a final dataframe ('creditscoring') right after creating the list.

3.1. Payment history

In [19]:
# I assume 60% have a payment history and 40% don't
creditscoring = ["Yes" for _ in range(int(k * 0.6))] + ["No" for _ in range(int(k * 0.4))]

random.shuffle(creditscoring)

In [20]:
creditscoring = pd.DataFrame(creditscoring)

In [21]:
creditscoring.rename(columns = {0: "paymenthistory"}, inplace = True)

In [22]:
# I create a 'sub-column' for all customers that have not paid their bills on time
creditscoring["nolatepayment"] = [None] * 1000

In [23]:
for i, value in enumerate(creditscoring["paymenthistory"]):
    if value == "No":
        creditscoring.loc[i, "nolatepayment"] = random.randint(1, 10) # number of times a payment was late

In [24]:
# I create another 'sub-column' for all customers that have not paid their bills on time
creditscoring["timelatepayment"] = [None] * 1000

In [25]:
for i, value in enumerate(creditscoring["paymenthistory"]):
    if value == "No":
        creditscoring.loc[i, "timelatepayment"] = random.randint(1, 52) # average weeks the payment was late

3.2. Amounts Owed

This is composed of credit available and credit used.

3.2.1. Credit available

In [26]:
# Calculate the number of null values (10% of total indices)
num_nulls = int(k * 0.1)
num_integers = k - num_nulls
random_integers = [random.randint(1000, 500000) for _ in range(num_integers)]
prelim_data = random_integers + [None] * num_nulls
random.shuffle(prelim_data)

In [27]:
# Create a DataFrame with the column data
creditscoring["creditavailable"] = pd.DataFrame({'Column': prelim_data})

In [28]:
# check if indeed 100 people have no credit available
creditscoring["creditavailable"].isnull().sum()

100

3.2.2. Credit used

In [29]:
creditscoring["creditused"] = [None] * 1000

In [30]:
for i, value in enumerate(creditscoring["creditavailable"]):
    if value > 0:
        random_share = random.uniform(0.01, 1)  # Generate a random share between 0.01 and 1
        credit_used = random_share * value      # Calculate the credit used based on the random share
        credit_used = min(credit_used, value)   # Ensure credit_used is not larger than creditavailable
        creditscoring.loc[i, "creditused"] = credit_used

In [31]:
# make sure that creditavailable > creditused

# Create a boolean mask to filter out rows with missing values in either "creditavailable" or "creditused" column
valid_mask = creditscoring["creditavailable"].notnull() & creditscoring["creditused"].notnull()

# Check if "creditavailable" is always bigger than "creditused" in the valid rows
is_credit_valid = (creditscoring["creditavailable"][valid_mask] > creditscoring["creditused"][valid_mask]).all()

if is_credit_valid:
    print("All 'creditavailable' values are bigger than 'creditused'.")
else:
    print("There are 'creditused' values that are equal to or larger than 'creditavailable'.")

All 'creditavailable' values are bigger than 'creditused'.

3.3. Length of credit history

In [32]:
creditscoring["lengthcredithistory"] =[None] * 1000

In [33]:
for i, value in enumerate(details_df["Age"]):
    if not pd.isna(creditscoring["creditavailable"][i]):
        random_share = random.uniform(0.01, 0.2)
        creditscoring.loc[creditscoring.index[i], "lengthcredithistory"] = random_share * value

In [34]:
# The average length looks okay. Also, the current settings ensure that noone got a loan before turning 18
creditscoring["lengthcredithistory"].mean()

4.080126918161325

3.4. Credit mix

In [35]:
creditscoring["creditmix"] = [None] * 1000

In [36]:
for i, value in creditscoring["creditavailable"].items():
    if pd.isna(value):
        creditscoring.loc[i, "creditmix"] = np.nan
    else: creditscoring.loc[i, "creditmix"] = random.randint(1,4)

3.5. New credit

In [37]:
newcredit = [None] * 1000

In [38]:
newcredit = ["Yes" for _ in range(int(k * 0.4))] + ["No" for _ in range(int(k * 0.6))]

In [39]:
random.shuffle(newcredit)

In [40]:
creditscoring["newcredit"] = pd.DataFrame({'Column': newcredit})

In [41]:
creditscoring

,paymenthistory,nolatepayment,timelatepayment,creditavailable,creditused,lengthcredithistory,creditmix,newcredit
0,No,8,39,428445.0,296828.646112,3.222556,2,Yes
1,No,6,19,363420.0,197095.293621,2.397118,4,Yes
2,Yes,None,None,251810.0,206543.642966,2.380299,4,Yes
3,No,1,1,204560.0,59931.380523,1.653316,3,No
4,No,6,51,277439.0,161274.966325,4.384699,2,Yes
...,...,...,...,...,...,...,...,...
995,Yes,None,None,493137.0,242877.69975,3.204646,3,Yes
996,No,6,48,76420.0,27549.672982,3.935164,1,No
997,Yes,None,None,14696.0,3258.308631,1.910602,4,Yes
998,No,4,26,NaN,None,None,NaN,Yes
999,Yes,None,None,167011.0,44674.23752,10.394933,3,No

3.6. Create a dataframe with all generated data and save it as an excel file

This is important for the next sub-projects.

In [42]:
# create an ID column to be able to merge both datasets
creditscoring["ID"] = list(range(1,1001))

In [43]:
# merge datasets
merged_df = details_df.merge(creditscoring, left_on = "ID", right_on = "ID")

In [44]:
merged_df.head()

,ID,Age,City,Gender,paymenthistory,nolatepayment,timelatepayment,creditavailable,creditused,lengthcredithistory,creditmix,newcredit
0,1,23,Frankfurt,female,No,8,39,428445.0,296828.646112,3.222556,2,Yes
1,2,22,München,male,No,6,19,363420.0,197095.293621,2.397118,4,Yes
2,3,25,Hamburg,female,Yes,None,None,251810.0,206543.642966,2.380299,4,Yes
3,4,24,München,female,No,1,1,204560.0,59931.380523,1.653316,3,No
4,5,25,München,male,No,6,51,277439.0,161274.966325,4.384699,2,Yes

In [54]:
merged_df.to_excel("dataset.xlsx", index=False)

3.7. Match CreditScore class with merged_df dataframe

In [ ]:
credit_score_instances = []
for index, row in merged_df.iterrows():
    credit_score_instance = CreditScore(row['ID'], row['Age'], row['City'], row['Gender'])
    credit_score_instance.paymenthistory(row['paymenthistory'])
    credit_score_instance.nolatepayments(row['nolatepayment'])
    credit_score_instance.timelatepayments(row['timelatepayment'])
    # credit_score_instance.amountsowed(row['creditused'], row['creditavailable'])
    credit_score_instance.lengthcredithistory(row['lengthcredithistory'])
    credit_score_instance.creditmix(row['creditmix'])
    credit_score_instance.newcredit(row['newcredit'])
    credit_score_instances.append(credit_score_instance)

In [ ]:
for instance in credit_score_instances:
    print(f"User ID: {instance.ID}")
    print(f"Age: {instance.age}")
    print(f"City: {instance.city}")
    print(f"Gender: {instance.gender}")
    print(f"Payed Bills on Time: {instance.payment_history}")
    print(f"Number of Late Payments: {instance.nolatepayments}")
    print(f"Time of Late Payments: {instance.timelatepayments}")
    # print(f"Amount of Credit Used: {instance.credit_used}")
    # print(f"Total Credit Available: {instance.credit_available}")
    print(f"Length of Credit History: {instance.lengthcredithistory}")
    print(f"Credit Mix: {instance.creditmix}")
    print(f"New Credit: {instance.newcredit}")
    # print(f"Amounts Owed: {instance.amountsowed}")
    print("------------")